config/routes.rb
Rails.application.routes.draw do
  resources :shows
  devise_for :users
  root "shows#index"
  post "/mark_as_favourite/:show_id" => "shows#mark_as_favourite" ,:as=>:show_mark_as_favourite
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :shows
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :user
  belongs_to :show
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :channel
  has_many :favourites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favourites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.left_joins(:channel).all
    if params[:search].present?
      @shows = @shows.where("lower(shows.name) LIKE (?) OR lower(channels.name) LIKE (?)","%#{params[:search].strip.downcase}%","%#{params[:search].strip.downcase}%")
    end
  end
 

  def mark_as_favourite
    if params[:show_id].present?
      @favourite = Favourite.new
      @favourite.user_id = current_user.id
      @favourite.show_id = params[:show_id]
      if @favourite.save
        SendFavouriteShowWorker.perform_in(@favourite.show.play_time - 30.minutes, current_user.email, @favourite.show_id)

        flash[:success] = "Successfully marked as favourite"
      else
        flash[:error] = "Something went wrong"
      end
    else
      flash[:error] = "Parameters not present"
    end
    redirect_to shows_path
  end


  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def show_params
      params.require(:show).permit(:name, :play_time, :channel_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BuilderAiTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/shows/_form.html.erb
<%= form_with(model: show, local: true) do |form| %>
  <% if show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :play_time %>
    <%= form.datetime_select :play_time %>
  </div>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.select :channel_id ,options_for_select(Channel.all.pluck(:name,:id))%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<div class ="">
  <div class="search_form_div">
    <%= form_tag shows_path, :method => 'get' do %>
      <%= label_tag(:search , "Search by show name and channel name:") %>
      <p>
        <%= text_field_tag :search, params[:search] , :placeholder => 'Search by show name and channel name'  %>
        <%= submit_tag "Search",  :name => nil%>
        <% if params[:search].present? %>
        <a href="<%= shows_path %>">Clear</a>
          <% end %>
      </p>
    <% end %>
  </div>
  <table>
    <tbody>
    <tr>
      <th>Id</th>
      <th>Show Name</th>
      <th>Channel Name</th>
      <th>Show Timing</th>
      <th>Action</th>
    </tr>

      <% @shows.each do |show| %>
    <tr>
      <td><%= show.id %></td>
      <td><%= show.name %></td>
      <td><%= show.channel.name %></td>
      <td><%= show.play_time %></td>
      <td>

        <% unless show.favourites.pluck(:user_id).include?(current_user.id) %>
        <%= link_to "Mark as Favourite", show_mark_as_favourite_path(:show_id => show.id)  , :method => "post" %>
          <% end %>
      </td>
    </tr>
      <% end %>

    </tbody>
  </table>

</div>

app/views/shows/new.html.erb
<h1>New Show</h1>

<%= render 'form', show: @show %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @show.name %>
</p>

<p>
  <strong>Play time:</strong>
  <%= @show.play_time %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @show.channel_id %>
</p>

<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>